name: Tests

# This workflow runs standard unit tests to ensure basic integrity and avoid
# regressions on pull-requests (and pushes)

on:
  push:
    branches:
      - master
  pull_request:
    # runs on all PR that are not drafts
    # also runs on "synchronize" which means, when there is a push
    # to the current branch that is used to open the PR (target branch)
    types: [review_requested, ready_for_review, synchronize]

jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
    - name: Checkout ${{ matrix.node }}
      uses: actions/checkout@v2

    - name: Setup node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Yarn
      uses: bahmutov/npm-install@v1.4.0

    - name: Run tests
      run: yarn test
